all:
  children:
    vault_servers:
      hosts:
        vault-01:
          ansible_host: 192.168.92.141
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        vault-02:
          ansible_host: 192.168.92.130
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        vault-03:
          ansible_host: 192.168.92.131
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    haproxy_servers:
      hosts:
        haproxy-01:
          ansible_host: 192.168.92.129
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
